replaced hardcoded text with env variables
DjedAlliance/Djed-Solidity-WebDashboard pull request #60
Opened 2023-05-25 20:21 UTC by yogesh0509

I have replaced some of the texts that I found were not generic and were hard coded to the Milkomeda-C1 testnet.
Please let me know if any more changes are required.

2023-05-26 06:01 UTC, ceilican requested changes
Thanks, @yogesh0509 !

I have only one simple change request on this PR.

There are also some other files that contain hard-coded content. But we can change them in a different PR. I will write about them in issue #51 .

2023-05-26 09:31 UTC, yogesh0509 commented on src/components/molecules/BuySellCoin/BuySellCoin.jsx
> +          Please change your MetaMask {process.env.REACT_APP_BC} network to Testnet and refresh the page.
Sure

2023-05-26 20:22 UTC, yogesh0509 commented on src/components/molecules/BuySellCoin/BuySellCoin.jsx
> +          Please change your MetaMask {process.env.REACT_APP_BC} network to Testnet and refresh the page.
I have changed the text as per the requirement. Can you review it again?

2023-05-26 20:39 UTC, yogesh0509 commented on src/components/molecules/BuySellCoin/BuySellCoin.jsx
> +          Please change your MetaMask {process.env.REACT_APP_BC} network to Testnet and refresh the page.
I have also made changes as requested for the other files. Should I push them now so that it can be merged with this pull request?

2023-05-29 03:03 UTC, ceilican approved these changes

2023-05-29 03:03 UTC, merged