readmeUpdated
DjedAlliance/Djed-Solidity-WebDashboard pull request #84
Opened 2023-06-20 07:49 UTC by roxor-dj

Updated readme file

2023-06-20 08:08 UTC, ceilican commented on README.md
> +#### `npm run format`
Here too.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +#### `npm run build`
Here too.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +#### `npm run eject`
Here too.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +#### Milkomeda docs
Remove this subsection.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +#### Djed docs
Let's remove this line.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +Documentation lives on [**Djed docs**](https://docs.djed.one/alliance/the-djed-alliance).
Let's move this line to the "What is Djed?" section in the beginning.

2023-06-20 08:08 UTC, ceilican commented on README.md
> +
Could you add some interesting badges/shield in the beginning of the readme?  Have a look here (https://shields.io/) to see how to do it.

2023-06-23 14:47 UTC, roxor-dj commented on README.md
> +#### Getting Started with Create React App
Should I remove here all lines from 22 - 25, or just 25? @ceilican

2023-06-26 06:45 UTC, ceilican requested changes

2023-06-26 06:45 UTC, ceilican commented on README.md
> +Here you can interact with a deployment that uses [these smart contracts](https://github.com/DjedAlliance/Djed-Solidity/commits/Belus) on Milkomeda-C1.
Yes, let's delete this paragraph too.

2023-06-26 06:45 UTC, ceilican commented on README.md
> +
OK. Let's leave shields to another PR.

2023-06-26 06:45 UTC, ceilican commented on README.md
>  ### `npm start`
Use triple backquotes (```) instead of a header (###) here.

2023-06-26 06:45 UTC, ceilican commented on README.md
>  ### `npm start`
Also for "### `npm test`", "### `npm run format`", run build, run eject.

2023-07-03 08:34 UTC, ceilican approved these changes

2023-07-03 08:35 UTC, merged